import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/components/Theme/ThemeProvider";
import AppBar from "@/components/layout/AppBar";
import { ScrollProvider } from "@/components/layout/ScrollProvider";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="w-screen h-screen bg-background rounded-xl ">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ScrollProvider>
            <div className="flex flex-col">
              <AppBar />
              <main className="flex-grow md:overflow-x-auto md:overflow-y-hidden  overflow-y-auto flex scroll-smooth snap-x snap-mandatory no-scrollbar">
                {children}
              </main>
              <Footer />
            </div>
          </ScrollProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
