import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/components/Theme/ThemeProvider";
import AppBar from "@/components/layout/AppBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-foreground mx-1 md:mx-4 my-2">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="w-full h-[98vh] bg-background rounded-xl pt-4 flex flex-col">
            <AppBar />
            <main className="flex-grow overflow-x-hidden">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
